repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # Pre-commit version v4.6.0
    rev: v6.0.0
    hooks:
    - id: check-yaml
      args: [ --allow-multiple-document ]
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version v0.6.7
    rev: v0.16.5
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python, pyi ]
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi ]
